//HintName: TemplateGeneratorLog.g.cs
//--- AutoGenerated info file. ---

//--- Log: ---

// [2026-01-22T19:33:57.7609559+01:00 | Trace] Registering attribute generator 'ComponentGenerator'
// [2026-01-22T19:33:57.7621446+01:00 | Trace] Registering generator 'ArchTypeGenerator'
// [2026-01-22T19:33:57.7624151+01:00 | Trace] Registering attribute generator 'SystemGenerator'
// [2026-01-22T19:33:57.7626188+01:00 | Trace] Registering attribute generator 'SystemGenerator'
// [2026-01-22T19:33:57.7628683+01:00 | Trace] Registering attribute generator 'SystemGenerator'
// [2026-01-22T19:33:57.7630538+01:00 | Trace] Registering attribute generator 'SystemGenerator'
// [2026-01-22T19:33:57.7632730+01:00 | Trace] Registering attribute generator 'SystemGenerator'
// [2026-01-22T19:33:57.7634988+01:00 | Trace] Registering attribute generator 'SystemGenerator'
// [2026-01-22T19:33:57.7636933+01:00 | Trace] Registering generator 'WorldGenerator'
// [2026-01-22T19:33:57.7638814+01:00 | Trace] Registering generator 'EcsGenerator'
// [2026-01-22T19:33:57.7640695+01:00 | Trace] Registering attribute generator 'ResourceManagerGenerator'
// [2026-01-22T19:33:57.8286705+01:00 | Trace] Generator 'ComponentGenerator' will be run on node at 'SourceFile([1302..1401))' ('TestComp123')
// [2026-01-22T19:33:57.8294529+01:00 | Trace] Generator 'ComponentGenerator' will be run on node at 'SourceFile([1406..1524))' ('Position')
// [2026-01-22T19:33:57.8297649+01:00 | Trace] Generator 'ComponentGenerator' will be run on node at 'SourceFile([1727..1839))' ('Velocity')
// [2026-01-22T19:33:57.8453889+01:00 | Trace] Executing generator 'Component Generator (TestComp123) (SourceFile([1302..1401)))'
// [2026-01-22T19:33:57.8796134+01:00 | Trace] Generator finished
// [2026-01-22T19:33:57.8863173+01:00 | Trace] Executing generator 'Component Generator (Position) (SourceFile([1406..1524)))'
// [2026-01-22T19:33:57.8896006+01:00 | Trace] Generator finished
// [2026-01-22T19:33:57.8901039+01:00 | Trace] Executing generator 'Component Generator (Velocity) (SourceFile([1727..1839)))'
// [2026-01-22T19:33:57.9061567+01:00 | Trace] Generator finished
// [2026-01-22T19:33:57.9397761+01:00 | Trace] Generator 'ArchTypeGenerator' will be run on node at 'SourceFile([4106..4116))'
// [2026-01-22T19:33:57.9848850+01:00 | Trace] Generator 'WorldGenerator' will be run on node at 'SourceFile([4106..4116))'
// [2026-01-22T19:33:57.9959832+01:00 | Trace] Generator 'EcsGenerator' will be run on node at 'SourceFile([4106..4116))'
// [2026-01-22T19:33:58.0099559+01:00 | Trace] Executing generator 'Component Generator (Runner.Ecs) (SourceFile([4102..4705)))'
// [2026-01-22T19:33:58.0176633+01:00 | Trace] Generator finished
// [2026-01-22T19:33:58.0237868+01:00 | Trace] Generator 'SystemGenerator' will be run on node at 'SourceFile([1844..2277))' ('PerfSystem')
// [2026-01-22T19:33:58.0254482+01:00 | Trace] Generator 'SystemGenerator' will be run on node at 'SourceFile([2282..2906))' ('PositionSystem')
// [2026-01-22T19:33:58.0257953+01:00 | Trace] Generator 'SystemGenerator' will be run on node at 'SourceFile([2911..3226))' ('PrintSystem')
// [2026-01-22T19:33:58.0261098+01:00 | Trace] Generator 'SystemGenerator' will be run on node at 'SourceFile([3231..3605))' ('PrintSystem_2')
// [2026-01-22T19:33:58.0264557+01:00 | Trace] Generator 'SystemGenerator' will be run on node at 'SourceFile([3610..3923))' ('LayerSystem')
// [2026-01-22T19:33:58.0399204+01:00 | Trace] Executing generator 'Component Generator (PerfSystem) (SourceFile([1844..2277)))'
// [2026-01-22T19:33:58.0513934+01:00 | Trace] Generator finished
// [2026-01-22T19:33:58.0518679+01:00 | Trace] Executing generator 'Component Generator (PositionSystem) (SourceFile([2282..2906)))'
// [2026-01-22T19:33:58.0578039+01:00 | Trace] Generator finished
// [2026-01-22T19:33:58.0581330+01:00 | Trace] Executing generator 'Component Generator (PrintSystem) (SourceFile([2911..3226)))'
// [2026-01-22T19:33:58.0619927+01:00 | Trace] Generator finished
// [2026-01-22T19:33:58.0622755+01:00 | Trace] Executing generator 'Component Generator (PrintSystem_2) (SourceFile([3231..3605)))'
// [2026-01-22T19:33:58.0661274+01:00 | Trace] Generator finished
// [2026-01-22T19:33:58.0686865+01:00 | Trace] Executing generator 'Component Generator (LayerSystem) (SourceFile([3610..3923)))'
// [2026-01-22T19:33:58.0729009+01:00 | Trace] Generator finished
// [2026-01-22T19:33:58.0872235+01:00 | Trace] Executing generator 'Component Generator (Runner.Ecs) (SourceFile([4102..4705)))'
// [2026-01-22T19:33:58.0968702+01:00 | Trace] Generator finished
// [2026-01-22T19:33:58.1070155+01:00 | Trace] Executing generator 'Component Generator (Runner.Ecs) (SourceFile([4102..4705)))'
// [2026-01-22T19:33:58.1100757+01:00 | Trace] Generator finished
// [2026-01-22T19:33:58.1164399+01:00 | Trace] Generator 'ResourceManagerGenerator' will be run on node at 'SourceFile([593..1297))' ('MeshResourceManager')
// [2026-01-22T19:33:58.1269842+01:00 | Trace] Executing generator 'Component Generator (MeshResourceManager) ()'
// [2026-01-22T19:33:58.1296119+01:00 | Trace] Generator finished
