//HintName: TemplateGeneratorLog.g.cs
//--- AutoGenerated info file. ---

//--- Log: ---

// [2025-11-01T19:24:24.6489727+01:00 | Trace] Registering attribute generator 'ComponentGenerator'
// [2025-11-01T19:24:24.6508742+01:00 | Trace] Registering generator 'ArchTypeGenerator'
// [2025-11-01T19:24:24.6511113+01:00 | Trace] Registering attribute generator 'SystemGenerator'
// [2025-11-01T19:24:24.6512768+01:00 | Trace] Registering attribute generator 'SystemGenerator'
// [2025-11-01T19:24:24.6514600+01:00 | Trace] Registering attribute generator 'SystemGenerator'
// [2025-11-01T19:24:24.6516355+01:00 | Trace] Registering attribute generator 'SystemGenerator'
// [2025-11-01T19:24:24.6518346+01:00 | Trace] Registering attribute generator 'SystemGenerator'
// [2025-11-01T19:24:24.6520146+01:00 | Trace] Registering attribute generator 'SystemGenerator'
// [2025-11-01T19:24:24.6521917+01:00 | Trace] Registering generator 'WorldGenerator'
// [2025-11-01T19:24:24.6523759+01:00 | Trace] Registering generator 'EcsGenerator'
// [2025-11-01T19:24:24.6526757+01:00 | Trace] Registering attribute generator 'ResourceManagerGenerator'
// [2025-11-01T19:24:24.7154715+01:00 | Trace] Generator 'ComponentGenerator' will be run on node at 'SourceFile([1363..1462))' ('TestComp123')
// [2025-11-01T19:24:24.7162110+01:00 | Trace] Generator 'ComponentGenerator' will be run on node at 'SourceFile([1467..1768))' ('Position')
// [2025-11-01T19:24:24.7165114+01:00 | Trace] Generator 'ComponentGenerator' will be run on node at 'SourceFile([1773..1973))' ('Velocity')
// [2025-11-01T19:24:24.7293520+01:00 | Trace] Executing generator 'Component Generator (TestComp123) (SourceFile([1363..1462)))'
// [2025-11-01T19:24:24.7671306+01:00 | Trace] Generator finished
// [2025-11-01T19:24:24.7716264+01:00 | Trace] Executing generator 'Component Generator (Position) (SourceFile([1467..1768)))'
// [2025-11-01T19:24:24.7857381+01:00 | Trace] Generator finished
// [2025-11-01T19:24:24.7861658+01:00 | Trace] Executing generator 'Component Generator (Velocity) (SourceFile([1773..1973)))'
// [2025-11-01T19:24:24.7885719+01:00 | Trace] Generator finished
// [2025-11-01T19:24:24.8202639+01:00 | Trace] Generator 'ArchTypeGenerator' will be run on node at 'SourceFile([4807..4817))'
// [2025-11-01T19:24:24.8619595+01:00 | Trace] Generator 'WorldGenerator' will be run on node at 'SourceFile([4807..4817))'
// [2025-11-01T19:24:24.8734765+01:00 | Trace] Generator 'EcsGenerator' will be run on node at 'SourceFile([4807..4817))'
// [2025-11-01T19:24:24.8872476+01:00 | Trace] Executing generator 'Component Generator (Runner.Ecs) (SourceFile([4803..5353)))'
// [2025-11-01T19:24:24.8952768+01:00 | Trace] Generator finished
// [2025-11-01T19:24:24.9018291+01:00 | Trace] Generator 'SystemGenerator' will be run on node at 'SourceFile([1978..2413))' ('PerfSystem')
// [2025-11-01T19:24:24.9026519+01:00 | Trace] Generator 'SystemGenerator' will be run on node at 'SourceFile([2418..3003))' ('PositionSystem')
// [2025-11-01T19:24:24.9029111+01:00 | Trace] Generator 'SystemGenerator' will be run on node at 'SourceFile([3008..3261))' ('PrintSystem')
// [2025-11-01T19:24:24.9031727+01:00 | Trace] Generator 'SystemGenerator' will be run on node at 'SourceFile([3266..3584))' ('LayerSystem')
// [2025-11-01T19:24:24.9052993+01:00 | Trace] Generator 'SystemGenerator' will be run on node at 'SourceFile([3589..4621))' ('ResourceSystem')
// [2025-11-01T19:24:24.9162690+01:00 | Trace] Executing generator 'Component Generator (PerfSystem) (SourceFile([1978..2413)))'
// [2025-11-01T19:24:24.9244513+01:00 | Trace] Generator finished
// [2025-11-01T19:24:24.9249599+01:00 | Trace] Executing generator 'Component Generator (PositionSystem) (SourceFile([2418..3003)))'
// [2025-11-01T19:24:24.9285943+01:00 | Trace] Generator finished
// [2025-11-01T19:24:24.9288346+01:00 | Trace] Executing generator 'Component Generator (PrintSystem) (SourceFile([3008..3261)))'
// [2025-11-01T19:24:24.9322535+01:00 | Trace] Generator finished
// [2025-11-01T19:24:24.9324688+01:00 | Trace] Executing generator 'Component Generator (LayerSystem) (SourceFile([3266..3584)))'
// [2025-11-01T19:24:24.9360618+01:00 | Trace] Generator finished
// [2025-11-01T19:24:24.9363232+01:00 | Trace] Executing generator 'Component Generator (ResourceSystem) (SourceFile([3589..4621)))'
// [2025-11-01T19:24:24.9409500+01:00 | Trace] Generator finished
// [2025-11-01T19:24:24.9618503+01:00 | Trace] Executing generator 'Component Generator (Runner.Ecs) (SourceFile([4803..5353)))'
// [2025-11-01T19:24:24.9718130+01:00 | Trace] Generator finished
// [2025-11-01T19:24:24.9819555+01:00 | Trace] Executing generator 'Component Generator (Runner.Ecs) (SourceFile([4803..5353)))'
// [2025-11-01T19:24:24.9842708+01:00 | Trace] Generator finished
// [2025-11-01T19:24:24.9902823+01:00 | Trace] Generator 'ResourceManagerGenerator' will be run on node at 'SourceFile([630..1358))' ('MeshResourceManager')
// [2025-11-01T19:24:25.0015095+01:00 | Trace] Executing generator 'Component Generator (MeshResourceManager) ()'
// [2025-11-01T19:24:25.0045027+01:00 | Trace] Generator finished
