//HintName: TemplateGeneratorLog.g.cs
// AutoGenerated log file.

// [2025-05-30T18:31:14.8012561+02:00 | Trace] Registering attribute generator 'ComponentGenerator'
// [2025-05-30T18:31:14.8047301+02:00 | Trace] Registering generator 'ArchTypeGenerator'
// [2025-05-30T18:31:14.8051389+02:00 | Trace] Registering attribute generator 'SystemGenerator'
// [2025-05-30T18:31:14.8054633+02:00 | Trace] Registering attribute generator 'SystemGenerator'
// [2025-05-30T18:31:14.8057558+02:00 | Trace] Registering attribute generator 'SystemGenerator'
// [2025-05-30T18:31:14.8060432+02:00 | Trace] Registering attribute generator 'SystemGenerator'
// [2025-05-30T18:31:14.8063174+02:00 | Trace] Registering attribute generator 'SystemGenerator'
// [2025-05-30T18:31:14.8065955+02:00 | Trace] Registering attribute generator 'SystemGenerator'
// [2025-05-30T18:31:14.8068412+02:00 | Trace] Registering generator 'WorldGenerator'
// [2025-05-30T18:31:14.8071413+02:00 | Trace] Registering generator 'EcsGenerator'
// [2025-05-30T18:31:14.8075439+02:00 | Trace] Registering attribute generator 'ResourceManagerGenerator'
// [2025-05-30T18:31:14.8687953+02:00 | Trace] Generator 'ComponentGenerator' will be run on node at 'SourceFile([1242..1341))' ('TestComp123')
// [2025-05-30T18:31:14.8695620+02:00 | Trace] Generator 'ComponentGenerator' will be run on node at 'SourceFile([1346..1647))' ('Position')
// [2025-05-30T18:31:14.8699311+02:00 | Trace] Generator 'ComponentGenerator' will be run on node at 'SourceFile([1652..1852))' ('Velocity')
// [2025-05-30T18:31:14.8807059+02:00 | Trace] Executing generator 'Component Generator (TestComp123) (SourceFile([1242..1341)))'
// [2025-05-30T18:31:14.9120325+02:00 | Trace] Generator finished
// [2025-05-30T18:31:14.9167867+02:00 | Trace] Executing generator 'Component Generator (Position) (SourceFile([1346..1647)))'
// [2025-05-30T18:31:14.9200945+02:00 | Trace] Generator finished
// [2025-05-30T18:31:14.9206979+02:00 | Trace] Executing generator 'Component Generator (Velocity) (SourceFile([1652..1852)))'
// [2025-05-30T18:31:14.9235780+02:00 | Trace] Generator finished
// [2025-05-30T18:31:14.9505051+02:00 | Trace] Generator 'ArchTypeGenerator' will be run on node at 'SourceFile([3649..3659))'
// [2025-05-30T18:31:14.9847535+02:00 | Trace] Generator 'WorldGenerator' will be run on node at 'SourceFile([3649..3659))'
// [2025-05-30T18:31:14.9950447+02:00 | Trace] Generator 'EcsGenerator' will be run on node at 'SourceFile([3649..3659))'
// [2025-05-30T18:31:15.0112727+02:00 | Trace] Executing generator 'Component Generator (Runner.Ecs) (SourceFile([3645..4195)))'
// [2025-05-30T18:31:15.0312178+02:00 | Trace] Generator finished
// [2025-05-30T18:31:15.0376302+02:00 | Trace] Generator 'SystemGenerator' will be run on node at 'SourceFile([1857..2292))' ('PerfSystem')
// [2025-05-30T18:31:15.0384624+02:00 | Trace] Generator 'SystemGenerator' will be run on node at 'SourceFile([2297..2882))' ('PositionSystem')
// [2025-05-30T18:31:15.0388752+02:00 | Trace] Generator 'SystemGenerator' will be run on node at 'SourceFile([2887..3140))' ('PrintSystem')
// [2025-05-30T18:31:15.0392825+02:00 | Trace] Generator 'SystemGenerator' will be run on node at 'SourceFile([3145..3463))' ('LayerSystem')
// [2025-05-30T18:31:15.0493034+02:00 | Trace] Executing generator 'Component Generator (PerfSystem) (SourceFile([1857..2292)))'
// [2025-05-30T18:31:15.0586072+02:00 | Trace] Generator finished
// [2025-05-30T18:31:15.0591796+02:00 | Trace] Executing generator 'Component Generator (PositionSystem) (SourceFile([2297..2882)))'
// [2025-05-30T18:31:15.0640210+02:00 | Trace] Generator finished
// [2025-05-30T18:31:15.0644724+02:00 | Trace] Executing generator 'Component Generator (PrintSystem) (SourceFile([2887..3140)))'
// [2025-05-30T18:31:15.0692356+02:00 | Trace] Generator finished
// [2025-05-30T18:31:15.0696825+02:00 | Trace] Executing generator 'Component Generator (LayerSystem) (SourceFile([3145..3463)))'
// [2025-05-30T18:31:15.0746893+02:00 | Trace] Generator finished
// [2025-05-30T18:31:15.0947995+02:00 | Trace] Executing generator 'Component Generator (Runner.Ecs) (SourceFile([3645..4195)))'
// [2025-05-30T18:31:15.1060266+02:00 | Trace] Generator finished
// [2025-05-30T18:31:15.1154734+02:00 | Trace] Executing generator 'Component Generator (Runner.Ecs) (SourceFile([3645..4195)))'
// [2025-05-30T18:31:15.1179737+02:00 | Trace] Generator finished
// [2025-05-30T18:31:15.1244606+02:00 | Trace] Generator 'ResourceManagerGenerator' will be run on node at 'SourceFile([509..1237))' ('MeshResourceManager')
// [2025-05-30T18:31:15.1359686+02:00 | Trace] Executing generator 'Component Generator (MeshResourceManager) ()'
// [2025-05-30T18:31:15.1402940+02:00 | Trace] Generator finished
